-- -- Create users table
-- CREATE TABLE users (
--     user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     username VARCHAR(50) UNIQUE NOT NULL,
--     email VARCHAR(255) UNIQUE NOT NULL,
--     password_hash VARCHAR(64) NOT NULL,
--     role VARCHAR(10) CHECK (role IN ('PLAYER', 'ADMIN')) NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- );

-- -- Create index on username and email for faster searches
-- CREATE INDEX idx_users_username ON users(username);
-- CREATE INDEX idx_users_email ON users(email);

-- -- Create player_profiles table
-- CREATE TABLE player_profiles (
--     profile_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     user_id UUID UNIQUE NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
--     first_name VARCHAR(50),
--     last_name VARCHAR(50),
--     date_of_birth DATE,
--     country VARCHAR(50),
--     bio TEXT,
--     current_rating FLOAT DEFAULT 1500,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- );

-- -- Create index on user_id for faster searches
-- CREATE INDEX idx_player_profiles_user_id ON player_profiles(user_id);